name: Terraform Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  TF_WORKING_DIR: ./infra

concurrency:
  group: terraform-deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::606349121896:role/GitHub_Actions_OIDC_Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Infrastructure Security Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: infra
          framework: terraform
          soft_fail: true

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Post Deploy Health Check
        working-directory: .
        run: |
          echo "Checking application health..."
          curl --fail --retry 10 --retry-delay 10 https://tools.osmanhus.co.uk