name: Terraform Destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  TF_WORKING_DIR: ./infra

concurrency:
  group: terraform-destroy
  cancel-in-progress: false

jobs:
  destroy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::606349121896:role/GitHub_Actions_OIDC_Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.8

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Destroy Plan
        run: terraform plan -destroy -out=destroy.tfplan

      - name: Terraform Destroy
        run: terraform apply -auto-approve destroy.tfplan