name: Terraform Plan

on:
  pull_request:
    branches: [main]
    paths:
      - "infra/**"
      - ".github/workflows/plan.yml"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  TF_WORKING_DIR: ./infra

jobs:
  plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::606349121896:role/GitHub_Actions_OIDC_Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.8

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Infrastructure Security Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: infra
          framework: terraform
          soft_fail: true

      - name: Terraform Plan
        run: terraform plan -var="image_tag=latest"
